name = "content-engine-trigger"
main = "content-engine-worker.js"
compatibility_date = "2025-06-05"

# This sets up the cron trigger to run every 2 minutes
# Format: "cron_expression"
# Current schedule: Every 2 minutes
[triggers]
crons = ["*/2 * * * *"]  # Every 2 minutes

# Set your environment variables
[vars]
ENVIRONMENT = "production"

# Secret environment variables (not exposed in the dashboard)
# After deployment, set these using the Cloudflare dashboard or Wrangler CLI:
# wrangler secret put API_KEY
# These are required for the Worker to authenticate with your API
# [secrets]
# API_KEY
